# Generated by Django 4.1.2 on 2022-10-10 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_address_zip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='zip',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
